[project]
name = "virtual-opioid-user"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.2"
dependencies = [
    "matplotlib>=3.9.2",
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "seaborn>=0.13.2",
    "streamlit>=1.39.0",
]
